# Usa H2 em memória (some ao terminar os testes)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=LEGACY

# Driver do H2
spring.datasource.driverClassName=org.h2.Driver

# Usuário e senha padrão do H2
spring.datasource.username=sa
spring.datasource.password=

# Mostra SQL no console (útil para debug)
spring.jpa.show-sql=true

# Cria o schema ao iniciar e apaga ao terminar
spring.jpa.hibernate.ddl-auto=create-drop

# Dialeto específico do H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Ativa console do H2 (opcional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console